/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.vcu.rewards.api;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RestController;

import com.vcu.rewards.business.CustomerRewardInfoService;
import com.vcu.rewards.model.RewardOption;

@RestController
public class CustomerRewardInfoController {

	@Autowired
	CustomerRewardInfoService customerRewardInfoService;
	
    @GetMapping(value = "/customers/{customerId}/rewards",
    produces = { "application/json" })
    public ResponseEntity<List<RewardOption>> getRewardOptions(@PathVariable Long customerId) {
    	return ResponseEntity.ok(customerRewardInfoService.getAllAvailableRewards(customerId));
    }
    
    @PutMapping(value = "/customers/{customerId}/creditcards/{creditCardId}/rewards/redeem")
    public void redeemMaximumReward(@PathVariable Long customerId, @PathVariable Long creditCardId) {
    	customerRewardInfoService.redeemReward(customerId, creditCardId);
    }
}